package LogIn_signUp;

/*
* The purpose of this class to display the sign up form, save the information
* into the database and give the user the option to choose their preference of
* pets.
* Last updated: 10/28/2020
* Author: Yngrid Corrales
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class NewUser extends javax.swing.JFrame {

    // Establishing connection to DatabaseConnector class
    Connection con = DatabaseConnector.connectdb();
    PreparedStatement ps = null;

    /**
     * Creates new form NewUser
     */
    public NewUser() {
        initComponents();
        DatabaseConnector.connectdb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jCheckBoxDogs = new javax.swing.JCheckBox();
        jCheckBoxCats = new javax.swing.JCheckBox();
        jCheckBoxBirds = new javax.swing.JCheckBox();
        jCheckBoxFish = new javax.swing.JCheckBox();
        jCheckBoxReptiles = new javax.swing.JCheckBox();
        jCheckBoxSmallF = new javax.swing.JCheckBox();
        jCheckBoxBarnyard = new javax.swing.JCheckBox();
        userEmail = new javax.swing.JTextField();
        userFN = new javax.swing.JTextField();
        userZip = new javax.swing.JTextField();
        userPhoneNo = new javax.swing.JTextField();
        userLN = new javax.swing.JTextField();
        userPassword = new javax.swing.JPasswordField();
        rePass = new javax.swing.JPasswordField();
        signUpButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        radius = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Email:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("First Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Phone Number:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Last Name:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Password:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Re-Type Password:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Zip Code:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Enter search radius:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Check boxes for desired pets:");

        jCheckBoxDogs.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jCheckBoxDogs.setText("Dogs");
        jCheckBoxDogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxDogsActionPerformed(evt);
            }
        });

        jCheckBoxCats.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jCheckBoxCats.setText("Cats");

        jCheckBoxBirds.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jCheckBoxBirds.setText("Birds");

        jCheckBoxFish.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jCheckBoxFish.setText("Fish");
        jCheckBoxFish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFishActionPerformed(evt);
            }
        });

        jCheckBoxReptiles.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jCheckBoxReptiles.setText("Reptiles");

        jCheckBoxSmallF.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jCheckBoxSmallF.setText("Small & Furry");

        jCheckBoxBarnyard.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jCheckBoxBarnyard.setText("Barnyard");

        signUpButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        signUpButton.setText("Sign Up");
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel11.setText("Range from 100-500miles");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Liz\\Downloads\\Screenshot 2020-10-28 202313.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(signUpButton)
                .addGap(104, 104, 104))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxBarnyard)
                            .addComponent(jCheckBoxSmallF)
                            .addComponent(jCheckBoxReptiles)
                            .addComponent(jCheckBoxFish)
                            .addComponent(jCheckBoxBirds)
                            .addComponent(jCheckBoxCats)
                            .addComponent(jCheckBoxDogs)
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(radius, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(userEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(userFN, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(userPassword, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(userZip, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rePass, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(userLN, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(userPhoneNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(56, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(3, 3, 3)
                        .addComponent(userEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(3, 3, 3)
                        .addComponent(userPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userLN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addGap(9, 9, 9)
                        .addComponent(rePass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(2, 2, 2)
                .addComponent(radius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addGap(38, 38, 38)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxDogs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxCats)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxBirds)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxFish)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxReptiles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxSmallF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxBarnyard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signUpButton)
                    .addComponent(cancelButton))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * When the user clicks on the sign up button, it saves all the data retrieved from
     * the user to the login database
     */
    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed

        // Creating strings from the JTextFields created in the JFrame
        String firstName = userFN.getText();
        String lastName = userLN.getText();
        String email = userEmail.getText();
        String phoneNumber = userPhoneNo.getText();
        String password = String.valueOf(userPassword.getPassword());
        String re_Pass = String.valueOf(rePass.getPassword());
        String zipCode = userZip.getText();
        String searchDistance = radius.getText();

        /**
         * Checks each JTextFields in this form to see if it's null and guards
         * against it
         */
        if (firstName.equals("")) {
            JOptionPane.showMessageDialog(null, "No first name added, add first name.");
        } else if (lastName.equals("")) {
            JOptionPane.showMessageDialog(null, "No last name added, add last name.");
        } else if (email.equals("")) {
            JOptionPane.showMessageDialog(null, "No email added, add email.");
        } else if (userPhoneNo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No phone number added, add phone number.");
        } else if (password.equals("")) {
            JOptionPane.showMessageDialog(null, "No password added, add password.");
        } else if (!password.equals(re_Pass)) {
            JOptionPane.showMessageDialog(null, "Password does not match, retype password.");
        } else if (re_Pass.equals("")) {
            JOptionPane.showMessageDialog(null, "Please type in the password for retype password.");
        } else if (userZip.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No zipcode added, add zipcode.");
        } else if (radius.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter a search radius.");

            /* Checks to see if search radius is within bounds */
        } else if (Integer.valueOf(radius.getText().toString()) < 100) {
            JOptionPane.showMessageDialog(null, "Out of bounds, please enter a search radius between 100-500miles");
        } else if (Integer.valueOf(radius.getText().toString()) > 500) {
            JOptionPane.showMessageDialog(null, "Out of bounds, please enter a search radius between 100-500miles");

        } else {

            // Updates the login database objects according to userSignUp table
            try {
                ps = con.prepareStatement("insert into userSignUp values(?,?,?,?,?,?,?)");
                ps.setString(1, firstName);
                ps.setString(2, lastName);
                ps.setString(3, email);
                ps.setString(4, phoneNumber);
                ps.setString(5, password);
                ps.setString(6, zipCode);
                ps.setString(7, searchDistance);
                ps.executeUpdate();

                // If successfully updated display message and SampleDisplay JFrame
                JOptionPane.showMessageDialog(this, "New user added");
                new SampleDisplay().setVisible(true);

            } catch (SQLException ex) {
                Logger.getLogger(NewUser.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_signUpButtonActionPerformed
    /* Exits the program*/
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void jCheckBoxFishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxFishActionPerformed

    private void jCheckBoxDogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDogsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxDogsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JCheckBox jCheckBoxBarnyard;
    private javax.swing.JCheckBox jCheckBoxBirds;
    private javax.swing.JCheckBox jCheckBoxCats;
    private javax.swing.JCheckBox jCheckBoxDogs;
    private javax.swing.JCheckBox jCheckBoxFish;
    private javax.swing.JCheckBox jCheckBoxReptiles;
    private javax.swing.JCheckBox jCheckBoxSmallF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField radius;
    private javax.swing.JPasswordField rePass;
    private javax.swing.JButton signUpButton;
    private javax.swing.JTextField userEmail;
    private javax.swing.JTextField userFN;
    private javax.swing.JTextField userLN;
    private javax.swing.JPasswordField userPassword;
    private javax.swing.JTextField userPhoneNo;
    private javax.swing.JTextField userZip;
    // End of variables declaration//GEN-END:variables
}
